/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava2;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.util.Collections.list;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.List;
import java.io.IOException;
import javax.swing.JList;
import com.toedter.calendar.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author K3NWAY
 */
 
public class AjoutProd extends javax.swing.JFrame {

    /**
     * Creates new form AjoutBrevet
     */
    Connection con; 
    Statement stmt;
    ResultSet rs;
    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
    return new java.sql.Date(date.getTime());
}
    /* Fonction De Connection */
private void DoConnect(){
        try{
           Class.forName("com.mysql.jdbc.Driver");
       Connection conn=null;
       
 String url="jdbc:mysql://localhost:3306/laboratoire"; 
 con=DriverManager.getConnection(url,"root","");
 stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
 
 JOptionPane.showMessageDialog(null, "Succes");
   
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }


    private String NomProd;
           private String typeProd;
           private String AbstractProd;
           private String MotcleProd;
           private String[] auteurs;
           private Date   dateProd;
           public static int index;
           private String codebrevet;
           private String TypeBrevet;
           private String NomRevue;
          private String typeRevue;
          private String NomConf;
          private String TypeComm;
          private String RangComm;
          private String NomEditeur;
          private String TitLiv;
          private String Cin;
          private String nomCher;
          private String path="";
          private String ext="";
          /*private List listNomCherch=new List();
          private List listPrenCherch=new List();
          private List listCin=new List();*/
          
    public AjoutProd() {
        initComponents();
        JButtonAjouter.setEnabled(false);
       for(int i=0;i<jTabbedPane7.getTabCount();i++){
         jTabbedPane7.setEnabledAt(i, false);
       }
       DoConnect();
         try{
            // con = DriverManager.getConnection("jdbc:mysql://localhost/test_db","root","");
             Statement st = con.createStatement();
             rs = st.executeQuery("select * from chercheur");
             
             while(rs.next()){
                 listCin.add(rs.getString("cin"));
                 listNomCherch.add(rs.getString("nom"));
                 listPrenCherch.add(rs.getString("prenom"));
                 
                 //listCin.select(-1);
             }
             ResultSet rs1=st.executeQuery("SELECT * from livre ");
             while(rs1.next()){
                jlistNomLivre.add(rs1.getString("titre"));
             }
             
         }catch(Exception ex){
             ex.printStackTrace();
         }
       
       //jTabbedPane7.setEnabled(false);
    }

    /**
     * This method path called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method path always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButtonAjouter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextNomProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JcombotypeProd = new javax.swing.JComboBox<>();
        JButtonSuivant = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        JCalCmbProd = new org.freixas.jcalendar.JCalendarCombo();
        jlblimport = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextMotCle = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        listCin = new java.awt.List();
        listNomCherch = new java.awt.List();
        listPrenCherch = new java.awt.List();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAbstract = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jbtnimport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextCode = new javax.swing.JTextField();
        jComboTypeBrevet = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonReturn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtextNomRevue = new javax.swing.JTextField();
        jcomboTypeRevue = new javax.swing.JComboBox<>();
        jButtonReturn2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtextNomConf = new javax.swing.JTextField();
        JcomboTypeComm = new javax.swing.JComboBox<>();
        jcomboRang = new javax.swing.JComboBox<>();
        jButtonReturn1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jNomLivre = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtextEditeurChap = new javax.swing.JTextField();
        jButtonReturn3 = new javax.swing.JButton();
        jlistNomLivre = new java.awt.List();
        jtextNomChap = new javax.swing.JTextField();
        jNomChap = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtextEditeurLivre = new javax.swing.JTextField();
        jButtonReturn4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter une production");
        setResizable(false);
        setSize(new java.awt.Dimension(200, 200));

        JButtonAjouter.setText("<html> <b> Ajouter<b>");
        JButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAjouterActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("<html> <b>Nom De production</b>");

        jLabel1.setText("<html><b>Type de Production");

        JcombotypeProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir Un element", "Brevet", "Article", "Communication", "Chapitre", "Livre" }));

        JButtonSuivant.setText("<html> <b>Suivant</b>");
        JButtonSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSuivantActionPerformed(evt);
            }
        });

        jLabel14.setText("<html> <b> Date De Production");

        JCalCmbProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCalCmbProdActionPerformed(evt);
            }
        });

        jlblimport.setText("<html> <b> Importer");

        jLabel18.setText("<html> <b> Mots Clés");

        jTextMotCle.setColumns(20);
        jTextMotCle.setRows(5);
        jScrollPane1.setViewportView(jTextMotCle);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Choisir le/les cin d'/ des auteur(s)"));

        listCin.setMultipleMode(true);

        listNomCherch.setMultipleMode(false);

        listPrenCherch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel17.setText("<html><b> Prenom Du Chercheur");

        jLabel15.setText("<html> <b> Nom du Chercheur");

        jLabel16.setText("<html> <b> Num Cin");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listCin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listNomCherch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPrenCherch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listNomCherch, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listCin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPrenCherch, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextAbstract.setColumns(20);
        jTextAbstract.setRows(5);
        jScrollPane2.setViewportView(jTextAbstract);

        jLabel19.setText("<html> <b> Abstract");

        jbtnimport.setText("<html><b>Importer le Fichier");
        jbtnimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JCalCmbProd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcombotypeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblimport)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jLabel19))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnimport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButtonSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(JButtonSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblimport, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnimport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JcombotypeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCalCmbProd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane7.addTab("Ajouter Une Nouvelle Production", jPanel2);

        jLabel4.setText("<html> <b>Code du Brevet</b>");

        jComboTypeBrevet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "National", "International" }));

        jLabel5.setText("<html> <b>Type de Brevet</b>");

        jButtonReturn.setText("<html><b> Retour");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCode, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTypeBrevet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(428, 428, 428))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCode, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTypeBrevet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jTabbedPane7.addTab("Brevet", jPanel3);

        jLabel3.setText("<html> <b> Nom De Revue<b>");

        jLabel7.setText("<html> <b> Type<b>");

        jcomboTypeRevue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non Indexée", "Indexée", "Indexée avec Impact Factor", " " }));

        jButtonReturn2.setText("<html><b> Retour");
        jButtonReturn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtextNomRevue, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jcomboTypeRevue, 0, 1, Short.MAX_VALUE))
                .addContainerGap(518, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReturn2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextNomRevue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboTypeRevue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jButtonReturn2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        jTabbedPane7.addTab("Article", jPanel4);

        jLabel8.setText("<html><b>Nom De Conference");

        jLabel9.setText("<html><b>Type");

        jLabel10.setText("<html><b>Rang");

        JcomboTypeComm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "National", "International" }));

        jcomboRang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classe A+", "Classe A", "Classe B", "Classe C", "Non Classé", " " }));

        jButtonReturn1.setText("<html><b> Retour");
        jButtonReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcomboRang, 0, 87, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtextNomConf, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(JcomboTypeComm, 0, 1, Short.MAX_VALUE))))
                .addContainerGap(563, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReturn1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtextNomConf)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JcomboTypeComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboRang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(jButtonReturn1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        jTabbedPane7.addTab("Communication", jPanel5);

        jNomLivre.setText("<html><b>Nom Du Livre");

        jLabel12.setText("<html><b>Editeur");

        jButtonReturn3.setText("<html><b> Retour");
        jButtonReturn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturn3ActionPerformed(evt);
            }
        });

        jNomChap.setText("<html><b>Nom Du Chapitre");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jNomLivre)
                    .addComponent(jNomChap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlistNomLivre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jtextEditeurChap, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtextNomChap, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(474, 474, 474))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReturn3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNomChap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jtextNomChap)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlistNomLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNomLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextEditeurChap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jButtonReturn3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        jTabbedPane7.addTab("Chapitre", jPanel6);

        jLabel13.setText("<html><b>Editeur Du Livre");

        jButtonReturn4.setText("<html><b> Retour");
        jButtonReturn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextEditeurLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButtonReturn4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextEditeurLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                .addComponent(jButtonReturn4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jTabbedPane7.addTab("Livre", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Se deconnecter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(JButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(JButtonAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAjouterActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst;
            PreparedStatement pst1;
            PreparedStatement pst2;
            
               File f=new File(path);
               FileInputStream iss= new FileInputStream(f);   
        /*JOptionPane.showMessageDialog(null,NomProd+" "+typeProd+" "+dateProd);
            
         JOptionPane.showMessageDialog(null, String.join(" ", auteurs));
            JOptionPane.showMessageDialog(null, index);*/
        java.sql.Date datep=convertJavaDateToSqlDate(dateProd);
            switch(index){
             case 1:
                 
                 codebrevet=jTextCode.getText();
                 TypeBrevet=jComboTypeBrevet.getSelectedItem().toString();
                 if((codebrevet.isEmpty()))
                      JOptionPane.showMessageDialog(null,"Veuillez Ecrire Le code du brevet");
                 else if(jComboTypeBrevet.getSelectedIndex()<0){
                     
                      JOptionPane.showMessageDialog(null,"Veuillez Choisir Le type De brevet");
                 }
                 else{
                     
                    
                 pst=con.prepareStatement("INSERT INTO production values(?,?,?,?,?)");
                  pst1=con.prepareStatement("INSERT INTO prodchercheur values(?,?)");
                  pst2=con.prepareStatement("INSERT INTO brevet values(?,?,?)");
                  
                 pst.setDate(2, convertJavaDateToSqlDate(dateProd));
                 pst.setString(1, NomProd);
                 pst.setString(3,AbstractProd);
                 pst.setString(4,MotcleProd);
                 pst.setString(5,path);
                  pst.execute();
                  
                 for(int i=0;i<auteurs.length;i++){
                     pst1.setString(1,auteurs[i]);
                     
                      //pst1.setDate(2, convertJavaDateToSqlDate(dateProd) );
                      pst1.setString(2, NomProd);
                      pst1.execute();
                 }
                 
                     ////pst2.setDate(1, convertJavaDateToSqlDate(dateProd));
                 pst2.setString(1, NomProd);
                 pst2.setString(2, codebrevet);
                 pst2.setString(3,TypeBrevet);
                 pst2.execute();
                  JOptionPane.showMessageDialog(null,"Ajout effectué avec succès"); 
                 } // fin else
                 break;
             case 2:
                 
                 NomRevue=jtextNomRevue.getText();
                 typeRevue=jcomboTypeRevue.getSelectedItem().toString();
                 if((NomRevue.isEmpty())||jcomboTypeRevue.getSelectedIndex()<0)
                      JOptionPane.showMessageDialog(null,"Veuillez Remplir les champs manquants");
                 else{
                 
                 pst=con.prepareStatement("INSERT INTO production values(?,?,?,?,?)");
                  pst1=con.prepareStatement("INSERT INTO prodchercheur values(?,?)");
                pst2=con.prepareStatement("INSERT INTO ARTICLE VALUES(?,?,?)");
                pst.setDate(2, convertJavaDateToSqlDate(dateProd));
                 pst.setString(1, NomProd);
                 pst.setString(3,AbstractProd);
                 pst.setString(4,MotcleProd);
                   pst.setString(5,path);
                  pst.execute();
                   for(int i=0;i<auteurs.length;i++){
                     pst1.setString(1,auteurs[i]);
                     
                     // pst1.setDate(2, convertJavaDateToSqlDate(dateProd) );
                      pst1.setString(2, NomProd);
                      
                      pst1.execute();
                 }
                   //pst2.setDate(1, convertJavaDateToSqlDate(dateProd));
                  pst2.setString(1,NomProd);
                  pst2.setString(2,NomRevue);
                  pst2.setString(3,typeRevue);
                  pst2.execute();
                   JOptionPane.showMessageDialog(null,"Ajout effectué avec succès");
                 } //fin else
                 break; 
             case 3: //Communication
                 NomConf=jtextNomConf.getText();
                 TypeComm=JcomboTypeComm.getSelectedItem().toString();
                 RangComm=jcomboRang.getSelectedItem().toString();
                  if((NomConf.isEmpty())||JcomboTypeComm.getSelectedIndex()<0||(jcomboRang.getSelectedIndex()<0))
                      JOptionPane.showMessageDialog(null,"Veuillez Remplir les champs manquants");
                 else{
                   pst=con.prepareStatement("INSERT INTO production values(?,?,?,?,?)");
                  pst1=con.prepareStatement("INSERT INTO prodchercheur values(?,?)");
                pst2=con.prepareStatement("INSERT INTO communication VALUES(?,?,?,?)");
                
         
                pst.setDate(2, convertJavaDateToSqlDate(dateProd));
                 pst.setString(1, NomProd);
                 pst.setString(3,AbstractProd);
                 pst.setString(4,MotcleProd);
                   pst.setString(5,path);
                  pst.execute();
                for(int i=0;i<auteurs.length;i++){
                     pst1.setString(1,auteurs[i]);
                     
                    //  pst1.setDate(2, convertJavaDateToSqlDate(dateProd) );
                      pst1.setString(2, NomProd);
                      pst1.execute();
                 }
                   //pst2.setDate(1, convertJavaDateToSqlDate(dateProd));
                  pst2.setString(1,NomProd);
                  pst2.setString(2,NomConf);
                  pst2.setString(3,TypeComm);
                  pst2.setString(4,RangComm);
                  
                  pst2.execute();
                   JOptionPane.showMessageDialog(null,"Ajout effectué avec succès"); 
                  }//fin else
                 break;
             case 4: //Chapitre
                 if((jlistNomLivre.getSelectedIndex()<0)||(jtextEditeurChap.getText().isEmpty())){
                     JOptionPane.showMessageDialog(null,"Veuillez Remplir Les champs");
                 } else{
                 
                  TitLiv=jlistNomLivre.getSelectedItem().toString();
                 NomEditeur=jtextEditeurChap.getText();
                 String NomChap=jtextNomChap.getText();
                  pst=con.prepareStatement("INSERT INTO production values(?,?,?,?,?)");
                  pst1=con.prepareStatement("INSERT INTO prodchercheur values(?,?)");
                  pst2=con.prepareStatement("INSERT INTO chapitre values(?,?,?)");
                
         
                pst.setDate(2, convertJavaDateToSqlDate(dateProd));
                 pst.setString(1, NomProd);
                 pst.setString(3,AbstractProd);
                 pst.setString(4,MotcleProd);
                   pst.setString(5,path);
                  pst.execute();
                for(int i=0;i<auteurs.length;i++){
                     pst1.setString(1,auteurs[i]);
                    //  pst1.setDate(2, convertJavaDateToSqlDate(dateProd) );
                      pst1.setString(2, NomProd);
                      pst1.execute();
                 }
                   //pst2.setDate(1, convertJavaDateToSqlDate(dateProd));
                  pst2.setString(1,NomProd);
                  pst2.setString(2,TitLiv);
                  pst2.setString(3,NomEditeur);
                  
                  pst2.execute();
                   JOptionPane.showMessageDialog(null,"Ajout effectué avec succès"); 
                         
                 
                 }
                 break;
             case 5: //Livre
                 if(jtextEditeurLivre.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null,"Champs Editeur manquant");
                 }
                 else{
                     NomEditeur=jtextEditeurLivre.getText().toString();
                     pst=con.prepareStatement("INSERT INTO production values(?,?,?,?,?)");
                  pst1=con.prepareStatement("INSERT INTO prodchercheur values(?,?)");
                  pst2=con.prepareStatement("INSERT INTO livre values(?,?)");
                
         
                 pst.setDate(2, convertJavaDateToSqlDate(dateProd));
                 pst.setString(1, NomProd);
                 pst.setString(3,AbstractProd);
                 pst.setString(4,MotcleProd);
                   pst.setString(5,path);
                  pst.execute();
                for(int i=0;i<auteurs.length;i++){
                     pst1.setString(1,auteurs[i]);
                    //  pst1.setDate(2, convertJavaDateToSqlDate(dateProd) );
                      pst1.setString(2, NomProd);
                      pst1.execute();
                 }
                   //pst2.setDate(1, convertJavaDateToSqlDate(dateProd));
                  pst2.setString(1,NomProd);
                  pst2.setString(2,NomEditeur);
                  pst2.execute();
                  JOptionPane.showMessageDialog(null,"Ajout effectué avec succès");   
                 }
                 break;
         }    
         }
        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null,"Fichier Non Trouvé");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            //JOptionPane.showMessageDialog(this,e.getStackTrace() );
        }
        
        
        
    }//GEN-LAST:event_JButtonAjouterActionPerformed

    private void JButtonSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSuivantActionPerformed
        // TODO add your handling code here:
        
      
        final JFileChooser chooser = new JFileChooser( );
         auteurs = listCin.getSelectedItems();
            dateProd=JCalCmbProd.getDate();
             NomProd=jTextNomProd.getText();
             AbstractProd=jTextAbstract.getText();
             MotcleProd=jTextMotCle.getText();
             typeProd=JcombotypeProd.getSelectedItem().toString();
         index=JcombotypeProd.getSelectedIndex();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
         if (NomProd.isEmpty()){
              JOptionPane.showMessageDialog(null, "Veuillez Taper le Nom de Production");
         }
        else if   (index==0)
                 {
                    JOptionPane.showMessageDialog(null, "Veuillez Choisir le Type De Production");  
                 }
         else if(dateProd.after(date)){
             
              JOptionPane.showMessageDialog(null, "Date Invalide (Superieure à La date D'aujourd'hui)");
         }
         else if(listCin.getSelectedIndexes().length==0){
              JOptionPane.showMessageDialog(null, "Veuillez Choisir Le Cin de chercheur");
         }
                //||(typeProd.isEmpty())
         else if (path.isEmpty())
                                            
        {
            JOptionPane.showMessageDialog(null, "Veuillez Choisir le Fichier");
        }
         else if (AbstractProd.isEmpty()){
              JOptionPane.showMessageDialog(null, "Veuillez Taper l'abstract ");
         }
         else if (MotcleProd.isEmpty())
                                            
        {
            JOptionPane.showMessageDialog(null, "Veuillez Ecrire les mots clés");
        }
         
        else{
           
               
            //auteurs=jTextAreaNomAuteurs.getText().split(",");
             /* DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
            try {
                dateProd =formatter.parse(formatter.format(JDateProd.getDate()));
            } catch (ParseException ex) {
                //Logger.getLogger(AjoutProd.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex.getMessage());
            }*/
            
           
         //jTabbedPane7.setEnabledAt(1, true);
        jTabbedPane7.setSelectedIndex(JcombotypeProd.getSelectedIndex());
        jTabbedPane7.setEnabledAt(index, true);
        JButtonAjouter.setEnabled(true);
        
        }
    
    }//GEN-LAST:event_JButtonSuivantActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
 jTabbedPane7.setEnabledAt(index, false);
        jTabbedPane7.setSelectedIndex(0);        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturn1ActionPerformed
        // TODO add your handling code here:
         jTabbedPane7.setEnabledAt(index, false);
         jTabbedPane7.setSelectedIndex(0);  
    }//GEN-LAST:event_jButtonReturn1ActionPerformed

    private void jButtonReturn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturn2ActionPerformed
        // TODO add your handling code here:
         jTabbedPane7.setEnabledAt(index, false);
         jTabbedPane7.setSelectedIndex(0);  
    }//GEN-LAST:event_jButtonReturn2ActionPerformed

    private void jButtonReturn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturn3ActionPerformed
        // TODO add your handling code here:
         jTabbedPane7.setEnabledAt(index, false);
         jTabbedPane7.setSelectedIndex(0);  
    }//GEN-LAST:event_jButtonReturn3ActionPerformed

    private void jButtonReturn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturn4ActionPerformed
        // TODO add your handling code here:
       jTabbedPane7.setEnabledAt(index, false);
         jTabbedPane7.setSelectedIndex(0);  
    }//GEN-LAST:event_jButtonReturn4ActionPerformed

    private void jbtnimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimportActionPerformed
        // TODO add your handling code here:
        
        final JFileChooser chooser = new JFileChooser( );
        final JFrame frame=this;
        
FileNameExtensionFilter filter = new FileNameExtensionFilter("Text/PDF", "txt", "text","pdf");
chooser.setFileFilter(filter);
        jbtnimport.addActionListener((ActionEvent e) -> {
            int returnVal = chooser.showOpenDialog(frame);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
               /* System.out.println("You have selected the file: " +
                        chooser.getSelectedFile( ).getPath( ));*/
               path= chooser.getSelectedFile( ).getPath( );
               String filename=chooser.getSelectedFile( ).getName();
               //ext=filename.split(".")[filename.split(".").length-1];
               //ext=filename.substring(filename.lastIndexOf("."),filename.length());
                //System.out.println(ext);
            } else {
                System.out.println("nothing selected.");
            }
        });
    }//GEN-LAST:event_jbtnimportActionPerformed

    private void JCalCmbProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCalCmbProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCalCmbProdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new PrevChercheur().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) path not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAjouter;
    private javax.swing.JButton JButtonSuivant;
    private org.freixas.jcalendar.JCalendarCombo JCalCmbProd;
    private javax.swing.JComboBox<String> JcomboTypeComm;
    private javax.swing.JComboBox<String> JcombotypeProd;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JButton jButtonReturn1;
    private javax.swing.JButton jButtonReturn2;
    private javax.swing.JButton jButtonReturn3;
    private javax.swing.JButton jButtonReturn4;
    private javax.swing.JComboBox<String> jComboTypeBrevet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel jNomChap;
    private javax.swing.JLabel jNomLivre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTextArea jTextAbstract;
    private javax.swing.JTextField jTextCode;
    private javax.swing.JTextArea jTextMotCle;
    private javax.swing.JTextField jTextNomProd;
    private javax.swing.JButton jbtnimport;
    private javax.swing.JComboBox<String> jcomboRang;
    private javax.swing.JComboBox<String> jcomboTypeRevue;
    private javax.swing.JLabel jlblimport;
    private java.awt.List jlistNomLivre;
    private javax.swing.JTextField jtextEditeurChap;
    private javax.swing.JTextField jtextEditeurLivre;
    private javax.swing.JTextField jtextNomChap;
    private javax.swing.JTextField jtextNomConf;
    private javax.swing.JTextField jtextNomRevue;
    private java.awt.List listCin;
    private java.awt.List listNomCherch;
    private java.awt.List listPrenCherch;
    // End of variables declaration//GEN-END:variables
}
