/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava2;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import static projetjava2.AjoutMastere.HasAlphaNumeric;
import static projetjava2.AjoutMastere.isValidEmailId;
import static projetjava2.AjoutMastere.numerique;
import static projetjava2.AjoutMastere.valideAge;


/**
 *
 * @author Scofield
 */
public class AjoutEns extends javax.swing.JFrame {

    /**
     * Creates new form AjoutEns
     */
    Connection con; 
    Statement stmt;
    ResultSet rs;
    public AjoutEns() {
        initComponents();
       /* jButton1.setBackground(new Color(0,0,0,0));
        jButton2.setBackground(new Color(0,0,0,0));*/
        DoConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void DoConnect(){
        try{
           Class.forName("com.mysql.jdbc.Driver");
       Connection conn=null;
       
 String url="jdbc:mysql://localhost:3306/laboratoire"; 
 con=DriverManager.getConnection(url,"root","");
 stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
 
   
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        institut = new javax.swing.JTextField();
        universite = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        datedip = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        menu1.setLabel("File");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter un enseignant");
        setMinimumSize(new java.awt.Dimension(890, 510));
        setPreferredSize(new java.awt.Dimension(890, 510));
        setSize(new java.awt.Dimension(890, 510));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ajouter / Modifier un enseignant");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 10, 400, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(127, 80, 40, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(117, 130, 60, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(134, 170, 40, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(131, 210, 40, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Num Tel");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(118, 250, 50, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(139, 290, 30, 15);

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom);
        nom.setBounds(185, 73, 179, 30);
        getContentPane().add(prenom);
        prenom.setBounds(185, 121, 179, 30);
        getContentPane().add(age);
        age.setBounds(185, 159, 69, 30);
        getContentPane().add(email);
        email.setBounds(185, 197, 179, 30);
        getContentPane().add(tel);
        tel.setBounds(185, 239, 179, 30);
        getContentPane().add(cin);
        cin.setBounds(185, 277, 179, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Date Der Diplome");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 89, 107, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nature Der Diplome");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(418, 124, 119, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Grade");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(502, 162, 35, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Institut");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(489, 200, 48, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Université");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(477, 238, 60, 15);
        getContentPane().add(institut);
        institut.setBounds(579, 198, 192, 30);
        getContentPane().add(universite);
        universite.setBounds(579, 236, 192, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava2/images/users_add.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(422, 383, 160, 56);

        datedip.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(datedip);
        datedip.setBounds(579, 80, 142, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava2/images/update icon.png"))); // NOI18N
        jButton2.setText("Modifier");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(236, 382, 150, 58);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Photo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(499, 277, 38, 15);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(579, 275, 106, 30);

        jButton3.setText("Parcourir...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(725, 274, 87, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner", "These", "Habilitation" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(579, 122, 132, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner", "Maitre de conferences", "Maitre assistant", "Professeur" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(579, 160, 132, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Modifier");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(236, 341, 124, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ajouter");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(427, 341, 124, 23);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(790, -26, 100, 80);

        jLabel15.setIcon(new javax.swing.ImageIcon("F:\\PROJET JAVA 2\\ajout.jpg")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 890, 500);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Retourner vers le menu pricipal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Se deconnecter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser f=new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter( "jpg", "jpeg","png","gif");
        f.setFileFilter(filter);
        f.showOpenDialog(null);
        File file=f.getSelectedFile();
        String filename=file.getAbsolutePath();
        jTextField1.setText(filename);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PrevAdmin g=new PrevAdmin();
        g.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Login l=new Login();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String name=nom.getText().toString();
            String pren=prenom.getText().toString();
            String Age=age.getText().toString();
            String numtel=tel.getText().toString();
            String adremail=email.getText().toString();
            String CIN=cin.getText().toString();
            String nature=jComboBox1.getSelectedItem().toString();
            String Grade=jComboBox2.getSelectedItem().toString();
            String inst=institut.getText().toString();
            String univ=universite.getText().toString();
            String date=((JTextField)datedip.getDateEditor().getUiComponent()).getText();
            String photo=jTextField1.getText();
            
              boolean ok=true;
                    if(name.equals("") || HasAlphaNumeric(name)){
                    JOptionPane.showMessageDialog(this, " nom invalide");
                    ok=false;}
                    if(pren.equals("") || HasAlphaNumeric(pren)){
                         JOptionPane.showMessageDialog(this, "prenom invalide");
                           ok=false;}
                    if(Age.length()!=2 ||!numerique(Age) || !valideAge(Age)){
                             JOptionPane.showMessageDialog(this, "Age invalide");
                               ok=false;}
                    if(numtel.equals("")||!numerique(numtel)){
                         JOptionPane.showMessageDialog(this, "Numero du telephone invalide");
                           ok=false;}
                    if(!isValidEmailId(adremail)){
                    JOptionPane.showMessageDialog(this, "invaild email");
                      ok=false;}
                    if(!numerique(CIN)||CIN.length()!=8 ||cin.equals("00000000")){
                     JOptionPane.showMessageDialog(this, "invalid cin ");
                       ok=false;}
                    if(jComboBox1.getSelectedIndex()==0){
                         JOptionPane.showMessageDialog(this, "selectionner le nature du diplome");
                           ok=false;}
                    if(jComboBox2.getSelectedIndex()==0){
                        JOptionPane.showMessageDialog(this, "selectionner le grade");
                          ok=false;}
                    if(date.equals("")){
                    JOptionPane.showMessageDialog(this, "Vous devez saisir la date du dernier diplome");
                      ok=false;}
                    if(inst.equals("")||HasAlphaNumeric(inst)){
                        JOptionPane.showMessageDialog(this, "Vous devez saisir l'institut");
                          ok=false;}
                    if(univ.equals("")||HasAlphaNumeric(univ)){
                        JOptionPane.showMessageDialog(this, "Vous devez saisir l'institut");
                          ok=false;}
                   
           
            if(ok){
                PreparedStatement pst=con.prepareStatement("insert into chercheur values(?,?,?,?,?,?,?)");
                File f=new File(photo);
                FileInputStream inputStream= new FileInputStream(f);
                pst.setString(1, CIN);
                pst.setString(2, name);
                pst.setString(3, pren);
                pst.setString(4, numtel);
                pst.setString(5, adremail);
                pst.setString(6, Age);
                pst.setBlob(7, inputStream);
                pst.execute();
                PreparedStatement pst2=con.prepareStatement("insert into enseignant values(?,?,?,?,?,?,?)");
                pst2.setString(1, CIN);
                pst2.setString(2, date);
                pst2.setString(3, nature);
                pst2.setString(4, Grade);
                pst2.setString(5, inst);
                pst2.setString(6, univ);
                pst2.setString(7, "0");

                pst2.execute();
                JOptionPane.showMessageDialog(this, "Record inserted successfully");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String numtel=tel.getText();
        String adremail=email.getText();
        String CIN=cin.getText();
        String nature=jComboBox1.getSelectedItem().toString();
        String Grade=jComboBox2.getSelectedItem().toString();
        String inst=institut.getText();
        String univ=universite.getText();
        String date=((JTextField)datedip.getDateEditor().getUiComponent()).getText();
        String photo=jTextField1.getText();
        try{
            PreparedStatement st = con.prepareStatement("select * from chercheur where cin=? ");
            st.setString(1, CIN);
            rs=st.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "L'enseignant portant la cin numero "+CIN+" n'existe pas dans la base");
            }
            else{
                if(!numtel.equals("")){
                    if(!numerique(numtel) || numtel.length()!=8){
                        JOptionPane.showMessageDialog(this, "Num tel incorrecte");
                    }
                    else{
                        PreparedStatement statement = con.prepareStatement("update chercheur set tel=? where cin=?" );
                        statement.setString(1,numtel);
                        statement.setString(2, CIN);
                        statement.execute();
                    }
                }
                if(!adremail.equals("")){
                    if(!isValidEmailId(adremail))
                    JOptionPane.showMessageDialog(this, "Email incorrecte");
                    else{
                        PreparedStatement statement = con.prepareStatement("update chercheur set email=? where cin=? ");
                        statement.setString(1,adremail);
                        statement.setString(2, CIN);
                        statement.execute();
                    }
                }
                if(jComboBox1.getSelectedIndex()>0){
                    if(HasAlphaNumeric(nature)){
                        JOptionPane.showMessageDialog(this, "Nom encadreur incorrecte");
                    }
                    else{
                        PreparedStatement statement = con.prepareStatement("update enseignant set natureDerDiplome=? where cin=? ");
                        statement.setString(1,nature);
                        statement.setString(2, CIN);
                        statement.execute();
                    }
                }
                if(jComboBox2.getSelectedIndex()>0){
                    if(HasAlphaNumeric(Grade)){
                        JOptionPane.showMessageDialog(this, "Nom encadreur incorrecte");
                    }
                    else{
                        PreparedStatement statement = con.prepareStatement("update enseignant set grade=? where cin=? ");
                        statement.setString(1,Grade);
                        statement.setString(2, CIN);
                        statement.execute();
                    }
                }
                if(!inst.equals("")){
                    if(HasAlphaNumeric(inst)){
                        JOptionPane.showMessageDialog(this, "Nom encadreur incorrecte");
                    }
                    else{
                        PreparedStatement statement = con.prepareStatement("update enseignant set institut=? where cin=? ");
                        statement.setString(1,inst);
                        statement.setString(2, CIN);
                        statement.execute();
                    }
                }
                if(!univ.equals("")){
                    if(HasAlphaNumeric(univ)){
                        JOptionPane.showMessageDialog(this, "Nom encadreur incorrecte");
                    }
                    else{
                        PreparedStatement statement = con.prepareStatement("update enseignant set universite=? where cin=? ");
                        statement.setString(1,univ);
                        statement.setString(2, CIN);
                        statement.execute();
                    }
                }
                if(!date.equals("")){
                    PreparedStatement statement = con.prepareStatement("update enseignant set dateDerDiplome=? where cin=? ");
                    statement.setString(1,date);
                    statement.setString(2, CIN);
                    statement.execute();
                }
                if(!photo.equals("")){
                    File f=new File(photo);
                    FileInputStream inputStream= new FileInputStream(f);
                    PreparedStatement statement = con.prepareStatement("update chercheur set photo=? where cin=?");
                    statement.setBlob(1, inputStream);
                    statement.setString(2, CIN);
                    statement.execute();
                }

                JOptionPane.showMessageDialog(this, "record updated successfully");
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            nom.setEnabled(false);
            prenom.setEnabled(false);
            age.setEnabled(false);
            jButton2.setEnabled(true);
             jButton1.setEnabled(false);
            
        }
     
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         if(jRadioButton2.isSelected()){
              nom.setEnabled(true);
            prenom.setEnabled(true);
            cin.setEnabled(true);
            age.setEnabled(true);
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutEns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutEns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cin;
    private com.toedter.calendar.JDateChooser datedip;
    private javax.swing.JTextField email;
    private javax.swing.JTextField institut;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField universite;
    // End of variables declaration//GEN-END:variables
}
