/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava2;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import static projetjava2.AjoutMastere.HasAlphaNumeric;
import static projetjava2.AjoutMastere.isValidEmailId;
import static projetjava2.AjoutMastere.numerique;
import static projetjava2.AjoutMastere.valideAge;

/**
 *
 * @author Scofield
 */
public class AjoutDoct extends javax.swing.JFrame {

    /**
     * Creates new form AjoutDoct
     */
    Connection con; 
    Statement stmt;
    ResultSet rs;
    public AjoutDoct() {
        initComponents();
      //  jButton1.setBackground(new Color(0,0,0,0));
        //jButton2.setBackground(new Color(0,0,0,0));
        DoConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void DoConnect(){
        try{
          
       Connection conn=null;
    Class.forName("com.mysql.jdbc.Driver");    
 String url="jdbc:mysql://localhost:3306/laboratoire"; 
 con=DriverManager.getConnection(url,"root","");
 stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
 
   
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        mem = new javax.swing.JTextField();
        enc = new javax.swing.JTextField();
        aff = new javax.swing.JTextField();
        pays = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        datederins = new com.toedter.calendar.JDateChooser();
        datepremins = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter un doctorant");
        setMinimumSize(new java.awt.Dimension(890, 650));
        setSize(new java.awt.Dimension(850, 690));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ajout/Modifier un Doctorant");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 390, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 77, 27, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 47, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 160, 24, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 200, 31, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Num Tel");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(51, 237, 48, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(79, 281, 20, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date Prem Inscrit");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(465, 71, 107, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("DateDernier Inscrit");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(456, 114, 116, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Titre These");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(503, 165, 67, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nom Encadrant");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(477, 213, 93, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Affiliation");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(520, 300, 60, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Pays Co Encadrant");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 340, 114, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Statut");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 330, 41, 15);
        getContentPane().add(nom);
        nom.setBounds(133, 65, 190, 30);

        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        getContentPane().add(prenom);
        prenom.setBounds(133, 115, 190, 30);
        getContentPane().add(age);
        age.setBounds(134, 153, 50, 30);
        getContentPane().add(email);
        email.setBounds(134, 191, 235, 30);
        getContentPane().add(tel);
        tel.setBounds(134, 232, 180, 30);

        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });
        getContentPane().add(cin);
        cin.setBounds(134, 276, 180, 27);
        getContentPane().add(mem);
        mem.setBounds(607, 158, 270, 30);
        getContentPane().add(enc);
        enc.setBounds(607, 206, 230, 30);
        getContentPane().add(aff);
        aff.setBounds(610, 290, 182, 30);

        pays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paysActionPerformed(evt);
            }
        });
        getContentPane().add(pays);
        pays.setBounds(607, 333, 182, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("F:\\PROJET JAVA 2\\users_add.png")); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(195, 481, 150, 50);

        datederins.setDateFormatString("yyyy-MM-dd");
        datederins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datederinsMouseClicked(evt);
            }
        });
        getContentPane().add(datederins);
        datederins.setBounds(607, 109, 179, 20);

        datepremins.setDateFormatString("yyyy-MM-dd");
        datepremins.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datepreminsKeyPressed(evt);
            }
        });
        getContentPane().add(datepremins);
        datepremins.setBounds(607, 71, 179, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("F:\\PROJET JAVA 2\\update icon.png")); // NOI18N
        jButton2.setText("    Modifier");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 481, 150, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Photo");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(540, 260, 38, 15);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(607, 256, 77, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Parcourir..");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(702, 254, 106, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir votre statut", "Contrat Assistant", "Contrat Chercheur", "Contrat Assistant Permanent", "Aucun" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(130, 320, 182, 32);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Modifier");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(432, 431, 124, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ajouter");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(213, 431, 124, 23);

        jLabel16.setIcon(new javax.swing.ImageIcon("F:\\PROJET JAVA 2\\ajout.jpg")); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, -26, 890, 650);

        jMenu1.setText("File");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Retourner au menu principal");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Se deconnecter");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
              String name=nom.getText().toString();
              String pren=prenom.getText().toString();
              String Age=age.getText().toString();
              String numtel=tel.getText().toString();
              String adremail=email.getText().toString();
              String CIN=cin.getText().toString();
              String nomenc=enc.getText().toString();
              String memoire=mem.getText().toString();
              String PAYS=pays.getText().toString();
              String affil=aff.getText().toString();
              String STATUT=jComboBox1.getSelectedItem().toString();
              String photo=jTextField1.getText();
              
              String date1=((JTextField)datepremins.getDateEditor().getUiComponent()).getText();
              String date2=((JTextField)datederins.getDateEditor().getUiComponent()).getText();
              
              boolean ok=true;
                    if(name.equals("") || HasAlphaNumeric(name)){
                    JOptionPane.showMessageDialog(this, " nom invalide");
                    ok=false;}
                    if(pren.equals("") || HasAlphaNumeric(pren)){
                         JOptionPane.showMessageDialog(this, "prenom invalide");
                           ok=false;}
                    if(Age.length()!=2 ||!numerique(Age) || !valideAge(Age)){
                             JOptionPane.showMessageDialog(this, "Age invalide");
                               ok=false;}
                    if(numtel.equals("")||!numerique(numtel)){
                         JOptionPane.showMessageDialog(this, "Numero du telephone invalide");
                           ok=false;}
                    if(!isValidEmailId(adremail)){
                    JOptionPane.showMessageDialog(this, "invaild email");
                      ok=false;}
                    if(!numerique(CIN)||CIN.length()!=8 || cin.equals("00000000")){
                     JOptionPane.showMessageDialog(this, "invalid cin ");
                       ok=false;}
                    if(jComboBox1.getSelectedIndex()==0){
                         JOptionPane.showMessageDialog(this, "selectionner le statut");
                           ok=false;}
                    if(date1.equals("")){
                        JOptionPane.showMessageDialog(this, "choisir la date du premier insciption");
                          ok=false;}
                    if(date2.equals("")){
                        JOptionPane.showMessageDialog(this, "choisir la date du dernier insciption");
                          ok=false;}
                    if(memoire.equals("")){
                        JOptionPane.showMessageDialog(this, "saisir le titre du these");
                          ok=false;}
                     if(nomenc.equals("")){
                        JOptionPane.showMessageDialog(this, "donner le nom de l'encadrant");
                          ok=false;}
                      if(affil.equals("")){
                        JOptionPane.showMessageDialog(this, "saisir l'affiliation");
                          ok=false;}
                      if(photo.equals("")){
                        JOptionPane.showMessageDialog(this, "choisir une photo");
                          ok=false;}
              
              
              
              
              
              
              
              
              
              
              
            
              if(ok){
                  File f=new File(photo);
               FileInputStream inputStream= new FileInputStream(f);
                 
               PreparedStatement ts=con.prepareStatement("select lower(concat(c.prenom,' ',c.nom)) from chercheur c,enseignant e where c.cin=e.cin and lower(concat(c.prenom,' ',c.nom))=?");
               ts.setString(1, nomenc.toLowerCase());
                rs=ts.executeQuery();
                if(!rs.next()){
                    JOptionPane.showMessageDialog(this, "le nom de l'encadrant doit figurer dans la table enseignant");
                }
                else{
                 PreparedStatement pst=con.prepareStatement("insert into chercheur values(?,?,?,?,?,?,?)");
                 pst.setString(1, CIN);
                 pst.setString(2, name);
                 pst.setString(3, pren);
                 pst.setString(4, numtel);
                 pst.setString(5, adremail);
                 pst.setString(6, Age);
                 pst.setBlob(7, inputStream);
                 pst.execute();
                 PreparedStatement pst2=con.prepareStatement("insert into doctorant values(?,?,?,?,?,?,?,?)");
                 pst2.setString(1, CIN);
                 pst2.setString(2, date1);
                 pst2.setString(3, date2);
                 pst2.setString(4, memoire);
                 pst2.setString(5, nomenc);
                 pst2.setString(6, affil);
                 pst2.setString(7, PAYS);
                 pst2.setString(8, STATUT);
                 pst2.execute();
                 JOptionPane.showMessageDialog(this, "Record inserted successfully");
                }
        
    }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
              String numtel=tel.getText().toString();
              String adremail=email.getText().toString();
              String CIN=cin.getText().toString();
              String nomenc=enc.getText().toString();
              String memoire=mem.getText().toString();
              String PAYS=pays.getText().toString();
              String affil=aff.getText().toString();
              String STATUT=jComboBox1.getSelectedItem().toString();
              String date1=((JTextField)datepremins.getDateEditor().getUiComponent()).getText();
              String date2=((JTextField)datederins.getDateEditor().getUiComponent()).getText();
              String photo=jTextField1.getText();
              try{
                   PreparedStatement st = con.prepareStatement("select * from chercheur where cin=? ");
            st.setString(1, CIN);
            rs=st.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "L'enseignant portant la cin numero "+CIN+" n'existe pas dans la base");
            }
            else{
              if(!numtel.equals("")){
                  
                   if(!numerique(numtel) || numtel.length()!=8){
                  JOptionPane.showMessageDialog(this, "Num tel incorrecte");
              }
                   else{
                PreparedStatement statement = con.prepareStatement("update chercheur set tel=? where cin=?" );
               statement.setString(1,numtel);
               statement.setString(2, CIN);
               statement.execute();
                   }
            }
              if(!adremail.equals("")){
                   if(!isValidEmailId(adremail))
                      JOptionPane.showMessageDialog(this, "Email incorrecte");
                   else{
                PreparedStatement statement = con.prepareStatement("update chercheur set email=? where cin=? ");
               statement.setString(1,adremail);
               statement.setString(2, CIN);
               statement.execute();
                   }
            }
              if(!nomenc.equals("")){
                   if(HasAlphaNumeric(nomenc)){
                      JOptionPane.showMessageDialog(this, "Nom encadreur incorrecte");
                  }
                  else{
                        PreparedStatement ts=con.prepareStatement("select lower(concat(c.prenom,' ',c.nom)) from chercheur c,enseignant e where c.cin=e.cin and lower(concat(c.prenom,' ',c.nom))=?");
               ts.setString(1, nomenc.toLowerCase());
                rs=ts.executeQuery();
                if(!rs.next()){
                    JOptionPane.showMessageDialog(this, "le nom de l'encadrant doit figurer dans la table enseignant");
                }
                       
                else{      
                       
                       
                       
                PreparedStatement statement = con.prepareStatement("update doctorant set nomenc=? where cin=? ");
               statement.setString(1,nomenc);
               statement.setString(2, CIN);
               statement.execute();
                   }
                   }
            }
              if(!memoire.equals("")){
                PreparedStatement statement = con.prepareStatement("update doctorant set titreThese=? where cin=? ");
               statement.setString(1,memoire);
               statement.setString(2, CIN);
               statement.execute();
            }
              if(!affil.equals("")){
                PreparedStatement statement = con.prepareStatement("update doctorant set affiliation=? where cin=? ");
               statement.setString(1,affil);
               statement.setString(2, CIN);
               statement.execute();
            }
              if(jComboBox1.getSelectedIndex()!=0){
                PreparedStatement statement = con.prepareStatement("update doctorant set statut=? where cin=? ");
               statement.setString(1,adremail);
               statement.setString(2, CIN);
               statement.execute();
            }
              if(!PAYS.equals("")){
                PreparedStatement statement = con.prepareStatement("update doctorant set PaysCoEnc=? where cin=? ");
               statement.setString(1,PAYS);
               statement.setString(2, CIN);
               statement.execute();
               
            }
              if(!date1.equals("")){
                PreparedStatement statement = con.prepareStatement("update doctorant set datePremIns=? where cin=? ");
               statement.setString(1,date1);
               statement.setString(2, CIN);
               statement.execute();
               
            }
              if(!date2.equals("")){
                PreparedStatement statement = con.prepareStatement("update doctorant set datederIns=? where cin=? ");
               statement.setString(1,date2);
               statement.setString(2, CIN);
               statement.execute();
               
            }
               if(!photo.equals("")){
               File f=new File(photo);
               FileInputStream inputStream= new FileInputStream(f);
               PreparedStatement statement = con.prepareStatement("update chercheur set photo=? where cin=?");
               statement.setBlob(1, inputStream);
                statement.setString(2, CIN);
               statement.execute();
            }
              JOptionPane.showMessageDialog(this, "record updated successfully");
              }
              
              }catch(SQLException e){
                  JOptionPane.showMessageDialog(this, e.getMessage());
              }
              catch(IOException e){
                  JOptionPane.showMessageDialog(this, e.getMessage());
              }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser f=new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter( "jpg", "jpeg","png","gif");
        f.setFileFilter(filter);
        f.showOpenDialog(null);
        File file=f.getSelectedFile();
        String filename=file.getAbsolutePath();
        jTextField1.setText(filename);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        PrevAdmin p=new PrevAdmin();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Login l=new Login();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            nom.setEnabled(false);
            prenom.setEnabled(false);
            age.setEnabled(false);
            jButton2.setEnabled(true);
            jButton1.setEnabled(false);

        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()){
            nom.setEnabled(true);
            prenom.setEnabled(true);
            cin.setEnabled(true);
            age.setEnabled(true);
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void paysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paysActionPerformed

    private void datederinsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datederinsMouseClicked
        // TODO add your handling code here:
        DateFormat d=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        if(datepremins.getDate().after(date))
            JOptionPane.showMessageDialog(null, "Date invalide");
        
    }//GEN-LAST:event_datederinsMouseClicked

    private void datepreminsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datepreminsKeyPressed
        // TODO add your handling code here:
         DateFormat d=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        if(datepremins.getDate().after(date))
            JOptionPane.showMessageDialog(null, "Date invalide");
    }//GEN-LAST:event_datepreminsKeyPressed

    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutDoct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutDoct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutDoct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutDoct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutDoct().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aff;
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cin;
    private com.toedter.calendar.JDateChooser datederins;
    private com.toedter.calendar.JDateChooser datepremins;
    private javax.swing.JTextField email;
    private javax.swing.JTextField enc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mem;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pays;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
