/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava2;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author Scofield
 */

public class AjoutMastere extends javax.swing.JFrame {

    /**
     * Creates new form AjoutChercheur
     */
     Connection con; 
    Statement stmt;
    ResultSet rs;
    public AjoutMastere() {
        initComponents();
         /*jButton1.setBackground(new Color(0,0,0,0));
        jButton2.setBackground(new Color(0,0,0,0));*/
        DoConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void DoConnect(){
        try{
           Class.forName("com.mysql.jdbc.Driver");
       Connection conn=null;
       
 String url="jdbc:mysql://localhost:3306/laboratoire"; 
 con=DriverManager.getConnection(url,"root","");
 stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
 
   
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lieuins = new javax.swing.JTextField();
        enc = new javax.swing.JTextField();
        mem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter un etudiant mastere");
        setMinimumSize(new java.awt.Dimension(1020, 530));
        setPreferredSize(new java.awt.Dimension(1020, 530));
        setResizable(false);
        setSize(new java.awt.Dimension(1020, 530));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ajout/Modifier un étudiant en mastère");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 0, 480, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 70, 27, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 110, 47, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 150, 24, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 185, 50, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Num Tel");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 220, 48, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 260, 40, 15);

        nom.setPreferredSize(new java.awt.Dimension(10, 20));
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom);
        nom.setBounds(167, 57, 189, 30);
        getContentPane().add(prenom);
        prenom.setBounds(167, 99, 189, 30);
        getContentPane().add(age);
        age.setBounds(167, 137, 50, 30);
        getContentPane().add(email);
        email.setBounds(167, 175, 189, 30);
        getContentPane().add(tel);
        tel.setBounds(167, 213, 189, 30);
        getContentPane().add(cin);
        cin.setBounds(167, 259, 189, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date Derniere Inscrit");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 60, 127, 26);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Lieu Derniere Inscrit");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 110, 123, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Intitulé du memoire");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(520, 150, 122, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nom Encadrant");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(540, 190, 93, 15);
        getContentPane().add(lieuins);
        lieuins.setBounds(654, 101, 182, 30);
        getContentPane().add(enc);
        enc.setBounds(654, 177, 182, 30);
        getContentPane().add(mem);
        mem.setBounds(654, 139, 182, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("F:\\PROJET JAVA 2\\users_add.png")); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 370, 160, 60);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(654, 57, 182, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("F:\\PROJET JAVA 2\\update icon.png")); // NOI18N
        jButton2.setText("Modifier");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 370, 160, 60);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Photo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(590, 230, 38, 15);

        jButton3.setText("Parcourir...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(797, 215, 87, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(654, 216, 117, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Modifier");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(340, 320, 124, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ajouter");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(500, 320, 124, 23);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava2/images/ajout.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -26, 1020, 500);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Retourner vers le menu pricipal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Se deconnecter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
              String name=nom.getText().toString();
              String pren=prenom.getText().toString();
              String Age=age.getText().toString();
              String numtel=tel.getText().toString();
              String adremail=email.getText().toString();
              String CIN=cin.getText().toString();
              String nomenc=enc.getText().toString();
              String lieuderins=lieuins.getText().toString();
              String memoire=mem.getText().toString();
              String photo=jTextField1.getText();
              String date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
             
                  
               boolean ok=true;
                    if(name.equals("") || HasAlphaNumeric(name)){
                    JOptionPane.showMessageDialog(this, " nom invalide");
                    ok=false;}
                    if(pren.equals("") || HasAlphaNumeric(pren)){
                         JOptionPane.showMessageDialog(this, "prenom invalide");
                           ok=false;}
                    if(Age.length()!=2 ||!numerique(Age) || !valideAge(Age)){
                             JOptionPane.showMessageDialog(this, "Age invalide");
                               ok=false;}
                    if(numtel.equals("")||!numerique(numtel)){
                         JOptionPane.showMessageDialog(this, "Numero du telephone invalide");
                           ok=false;}
                    if(!isValidEmailId(adremail)){
                    JOptionPane.showMessageDialog(this, "invaild email");
                      ok=false;}
                    if(!numerique(CIN)||CIN.length()!=8 ||cin.equals("00000000")){
                     JOptionPane.showMessageDialog(this, "invalid cin ");
                       ok=false;}
                 
                    if(date.equals("")){
                        JOptionPane.showMessageDialog(this, "choisir la date du premier insciption");
                          ok=false;}
                    
                    if(memoire.equals("")){
                        JOptionPane.showMessageDialog(this, "saisir le titre du these");
                          ok=false;}
                     if(nomenc.equals("")){
                        JOptionPane.showMessageDialog(this, "donner le nom de l'encadrant");
                          ok=false;}
                      if(photo.equals("")){
                        JOptionPane.showMessageDialog(this, "choisir votre photo");
                          ok=false;}
                      if(lieuderins.equals("")){
                        JOptionPane.showMessageDialog(this, "sasir le lieu du dernier inscri");
                          ok=false;}
              
              
                
                  
                  
                 PreparedStatement pst=con.prepareStatement("insert into chercheur values(?,?,?,?,?,?,?)");
                 File f=new File(photo);
                 FileInputStream inputStream= new FileInputStream(f);
                 pst.setString(1, CIN);
                 pst.setString(2, name);
                 pst.setString(3, pren);
                 pst.setString(4, numtel);
                 pst.setString(5, adremail);
                 pst.setString(6, Age);
                 pst.setBlob(7, inputStream);
                 pst.execute();
                 PreparedStatement pst2=con.prepareStatement("insert into etmastere values(?,?,?,?,?)");
                 pst2.setString(1, CIN);
                 pst2.setString(2, date);
                 pst2.setString(3, lieuderins);
                 pst2.setString(4, memoire);
                 pst2.setString(5, nomenc);
                 pst2.execute();
                 JOptionPane.showMessageDialog(this, "Record inserted successfully");
                
              
              
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
              String numtel=tel.getText();
              String adremail=email.getText();
              String CIN=cin.getText();
              String lieu=lieuins.getText();
              String memoire=mem.getText();
              String nomenc=enc.getText();
              String date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
              String photo=jTextField1.getText();
               try{
                   PreparedStatement st = con.prepareStatement("select * from chercheur where cin=? ");
            st.setString(1, CIN);
            rs=st.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "L'enseignant portant la cin numero "+CIN+" n'existe pas dans la base");
            }
            else{
              if(!numtel.equals("")){
                 if(!numerique(numtel) || numtel.length()!=8){
                  JOptionPane.showMessageDialog(this, "Num tel incorrecte");
              }
                 else{
                PreparedStatement statement = con.prepareStatement("update chercheur set tel=? where cin=?" );
               statement.setString(1,numtel);
               statement.setString(2, CIN);
               statement.execute();
              }
            }
              if(!adremail.equals("")){
                  if(!isValidEmailId(adremail))
                      JOptionPane.showMessageDialog(this, "Email incorrecte");
                  else{
                PreparedStatement statement = con.prepareStatement("update chercheur set email=? where cin=? ");
               statement.setString(1,adremail);
               statement.setString(2, CIN);
               statement.execute();
                  }
            }
              if(!memoire.equals("")){
                PreparedStatement statement = con.prepareStatement("update etmastere set IntMemoire=? where cin=? ");
               statement.setString(1,memoire);
               statement.setString(2, CIN);
               statement.execute();
            }
              if(!date.equals("")){
                PreparedStatement statement = con.prepareStatement("update etmastere set dateDerIns=? where cin=? ");
               statement.setString(1,date);
               statement.setString(2, CIN);
               statement.execute();
            }
              if(!lieu.equals("")){
                PreparedStatement statement = con.prepareStatement("update etmastere set lieuDerIns=? where cin=? ");
               statement.setString(1,lieu);
               statement.setString(2, CIN);
               statement.execute();
            }
              if(!nomenc.equals("")){
                  if(HasAlphaNumeric(nomenc)){
                      JOptionPane.showMessageDialog(this, "Nom encadreur incorrecte");
                  }
                  else{
                PreparedStatement statement = con.prepareStatement("update etmastere set enc=? where cin=? ");
               statement.setString(1,nomenc);
               statement.setString(2, CIN);
               statement.execute();
                  }
            }
               if(!photo.equals("")){
               File f=new File(photo);
               FileInputStream inputStream= new FileInputStream(f);
               PreparedStatement statement = con.prepareStatement("update chercheur set photo=? where cin=?");
               statement.setBlob(1, inputStream);
                statement.setString(2, CIN);
               statement.execute();
            }
             
              
              JOptionPane.showMessageDialog(this, "record updated successfully");
              }
              
              }catch(SQLException e){
                  JOptionPane.showMessageDialog(this, e.getMessage());
              }
               catch(IOException e){
                  JOptionPane.showMessageDialog(this, e.getMessage());
              }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         JFileChooser f=new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter( "jpg", "jpeg","png","gif");
        f.setFileFilter(filter);
        f.showOpenDialog(null);
        File file=f.getSelectedFile();
        String filename=file.getAbsolutePath();
        jTextField1.setText(filename);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       PrevAdmin g=new PrevAdmin();
        g.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Login l=new Login();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            nom.setEnabled(false);
            prenom.setEnabled(false);
            age.setEnabled(false);
            jButton2.setEnabled(true);
            jButton1.setEnabled(false);

        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()){
            nom.setEnabled(true);
            prenom.setEnabled(true);
            cin.setEnabled(true);
            age.setEnabled(true);
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutMastere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutMastere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutMastere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutMastere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutMastere().setVisible(true);
            }
        });
    }
    public static boolean HasAlphaNumeric(String name){
	 boolean res = false;
	 if(name.matches("^.*[^a-zA-Z ].*$")||(name.matches("^[0-9]*$")))
	 res=true;
		return res;
			
}
    public static boolean numerique(String ch){
        boolean ok=true;
            int i=0;
            String chiffre="0123456789";
            while(i<ch.length() && ok==true){
                if(chiffre.indexOf(ch.charAt(i))==-1)
                    ok=false;
                else
                    i++;
            }
        
        return ok;
    }
    public static boolean valideAge(String age){
        boolean ok=true;
        if(numerique(age)){
            int Age=Integer.valueOf(age);
            if(Age<20 || Age >50)
                ok=false;
        }
        else
            ok=false;
        return ok;
    }
    public static boolean isValidEmailId(String email) {
        String emailPattern = "^[\\w!#$%&’*+/=?`{|}~^-]+(?:\\.[\\w!#$%&’*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
        Pattern p = Pattern.compile(emailPattern);
        Matcher m = p.matcher(email);
        return m.matches();
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField email;
    private javax.swing.JTextField enc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lieuins;
    private javax.swing.JTextField mem;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
