/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author K3NWAY
 */
public class ModifierProd extends javax.swing.JFrame {

     Connection con=null;
     Statement stmt;
         ResultSet rs;
         String rq1;
            String path;
         
    /**
     * Creates new form SupprimerProd
     */
         
    private void DoConnect(){
        try{
           Class.forName("com.mysql.jdbc.Driver");
      
       
 String url="jdbc:mysql://localhost:3306/laboratoire"; 
 con=DriverManager.getConnection(url,"root","");
 stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
  //Connection conn=null;
 JOptionPane.showMessageDialog(null, "Succes");
   
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    public ModifierProd() {
        DoConnect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtcin = new javax.swing.JTextField();
        lstprod = new java.awt.List();
        jtbnmodifier = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtoption = new javax.swing.JTextField();
        jbtnimport = new javax.swing.JButton();
        jcmbchoix = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("<html><b><u>Charger La liste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("<html><b><u>Code Chercheur");

        lstprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstprodActionPerformed(evt);
            }
        });

        jtbnmodifier.setText("<html><b>Modifier");
        jtbnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnmodifierActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Importer Fichier");

        jbtnimport.setText("Importer");
        jbtnimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimportActionPerformed(evt);
            }
        });

        jcmbchoix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abstract", "Mots Clés", "Nouvel Fichier" }));
        jcmbchoix.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbchoixItemStateChanged(evt);
            }
        });
        jcmbchoix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcmbchoixMouseClicked(evt);
            }
        });
        jcmbchoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbchoixActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Se deconnecter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lstprod, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(jtxtcin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtoption)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnimport, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcmbchoix, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jcmbchoix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtoption, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnimport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtcin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstprod, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtbnmodifier)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    lstprod.removeAll();
        try{
            
            // con = DriverManager.getConnection("jdbc:mysql://localhost/test_db","root","");
            Statement st = con.createStatement();
            String rq="SELECT * FROM production p,prodchercheur pc where pc.titre=p.titre and pc.cin='"+jtxtcin.getText()+"'";
         // String rq1="SELECT COUNT(*) FROM production p,prodchercheur pc where pc.titre=p.titre and pc.cin="+jtxtcin.getText();
          
            //int  ms = st.execute(rq);
         //rs=st.executeQuery(rq1);
         //int ms=rs.getInt(0);
            rs=st.executeQuery(rq);
           int ms=0;
            while(rs.next()){
                lstprod.add(rs.getString("Titre"));
               ms++;
                //listCin.select(-1);
            }
            if (ms==0) JOptionPane.showMessageDialog(null,"NOT EXIST");
            

        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lstprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstprodActionPerformed

    private void jtbnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnmodifierActionPerformed
        // TODO add your handling code here:
       
        String req="";
          String Abstract="";
        String Mocle="";
        String Titre="";
        if(lstprod.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(null,"Veuillez Selectionner un item");
        }
        
        else {
            Titre=lstprod.getSelectedItem();
            if(jcmbchoix.getSelectedItem().equals("Abstract")){
               Abstract=jtxtoption.getText();
                 if(Abstract.isEmpty()){
                      JOptionPane.showMessageDialog(null,"Veuillez Tapez L'abstract");
                 }else 
                req="UPDATE PRODUCTION "
                       + "SET abstract='"+Abstract+"' WHERE Titre='"+Titre+"'";
                 
               System.out.println(rq1);
               
               try {
                Statement st = con.createStatement();
                
              //String rq="DELETE  FROM production WHERE Titre="+lstprod.getSelectedItem();
              st.executeUpdate(req);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
               
               
            }else if(jcmbchoix.getSelectedItem().equals("Mots Clés")){
           Mocle=jtxtoption.getText();
                if(Mocle.isEmpty()){
                    
                    JOptionPane.showMessageDialog(null,"Veuillez Tapez Les mots clés");
                }else 
                    
           req="UPDATE PRODUCTION SET motcle='"+Mocle+"' WHERE Titre='"+Titre+"'";
            }else if(jcmbchoix.getSelectedItem().equals("Nouvel FIchier")){
                
                try {
                Statement st = con.createStatement();
                
              //String rq="DELETE  FROM production WHERE Titre="+lstprod.getSelectedItem();
              st.executeUpdate(req);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
                if(path.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Veuillez Choisir un fichier");
                }else 
                {
                    req="UPDATE PRODUCTION "
                       + "SET file='"+path+"' WHERE Titre='"+Titre+"'";
              
                try {
                     PreparedStatement ps=con.prepareStatement("UPDATE PRODUCTION set file=? where titre=?");
                     ps.setString(0,path);
                      ps.setString(1,Titre);
                      
                Statement st = con.createStatement();
                
              //String rq="DELETE  FROM production WHERE Titre="+lstprod.getSelectedItem();
            //  st.executeUpdate(req);
              ps.executeQuery();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
                }
                System.out.println(req);
                
                
            }
            
           
           
            
        }
        
    }//GEN-LAST:event_jtbnmodifierActionPerformed

    private void jcmbchoixItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbchoixItemStateChanged
        // TODO add your handling code here:
          
     
    }//GEN-LAST:event_jcmbchoixItemStateChanged

    private void jcmbchoixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmbchoixMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jcmbchoixMouseClicked

    private void jcmbchoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbchoixActionPerformed
       // TODO add your handling code here:
        
       if(jcmbchoix.getSelectedItem().equals("Nouvel Fichier"))
       jtxtoption.setEnabled(false);
        if((jcmbchoix.getSelectedItem().equals("Abstract"))||jcmbchoix.getSelectedItem().equals("Mots Clés")){
             jtxtoption.setEnabled(true);
        }
       
       
    }//GEN-LAST:event_jcmbchoixActionPerformed

    private void jbtnimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimportActionPerformed
        // TODO add your handling code here:
      
        
        final JFileChooser chooser = new JFileChooser( );
        final JFrame frame=this;
        
FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF","pdf");
chooser.setFileFilter(filter);
        jbtnimport.addActionListener((ActionEvent e) -> {
            int returnVal = chooser.showOpenDialog(frame);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
               /* System.out.println("You have selected the file: " +
                        chooser.getSelectedFile( ).getPath( ));*/
               path= chooser.getSelectedFile( ).getPath( );
               String filename=chooser.getSelectedFile( ).getName();
               //ext=filename.split(".")[filename.split(".").length-1];
               //ext=filename.substring(filename.lastIndexOf("."),filename.length());
                //System.out.println(ext);
                System.out.println(path);
            } else {
                System.out.println("nothing selected.");
            }
        });
             
        
    }//GEN-LAST:event_jbtnimportActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new PrevChercheur().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbtnimport;
    private javax.swing.JComboBox<String> jcmbchoix;
    private javax.swing.JButton jtbnmodifier;
    private javax.swing.JTextField jtxtcin;
    private javax.swing.JTextField jtxtoption;
    private java.awt.List lstprod;
    // End of variables declaration//GEN-END:variables
}
