/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava2;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Scofield
 */
public class RechercheChercheur extends javax.swing.JFrame {

    /**
     * Creates new form RechercheChercheur
     */
    Connection con; 
    Statement stmt;
    ResultSet rs;
    public RechercheChercheur() {
        initComponents();
        DoConnect();
        jButton1.setBackground(new Color(0,0,0,0));
       
    }
    private void DoConnect(){
        try{
           Class.forName("com.mysql.jdbc.Driver");
       Connection conn=null;
       
 String url="jdbc:mysql://localhost:3306/laboratoire"; 
 con=DriverManager.getConnection(url,"root","");
 stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
 
 
   
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
 
        
     
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 530));
        setResizable(false);
        setSize(new java.awt.Dimension(1130, 530));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Recherche d'un(des) chercheur(s)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(158, 11, 314, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Critere du recherche");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(19, 61, 141, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava2/images/find.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 110, 170, 140);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setText("CIN");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(19, 107, 45, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton3.setText("GRADE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(19, 148, 63, 23);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton4.setText("TYPE CHERCHEUR");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(19, 189, 121, 23);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton6.setText("NATURE DIPLOME");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(19, 230, 123, 23);

        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(233, 108, 130, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maitre Assistant", "Maitre de conferences", "Professeur" }));
        jComboBox1.setEnabled(false);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(233, 149, 132, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mastere", "Doctorant", "Enseignant", "Directeur" }));
        jComboBox2.setEnabled(false);
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(233, 190, 130, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "These", "Habilitation" }));
        jComboBox3.setEnabled(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(233, 231, 130, 20);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CIN", "NOM", "PRENOM", "AGE", "EMAIL", "TEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 1110, 230);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setText("TOUS LES CHERCHEURS");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(20, 270, 160, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava2/images/recherche.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -26, 1150, 550);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Se deconnecter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton3.isSelected()){
    jTextField1.setEnabled(false);
    
    
   jComboBox1.setEnabled(true);
    jComboBox2.setEnabled(false);
     jComboBox3.setEnabled(false);
    
    
}
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton4.isSelected()){
    jTextField1.setEnabled(false);
    
  
     jComboBox1.setEnabled(false);
      jComboBox2.setEnabled(true);
       jComboBox3.setEnabled(false);
    
}
        
        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
if(jRadioButton1.isSelected()){
    jTextField1.setEnabled(true);
   
  
    jComboBox1.setEnabled(false);
    jComboBox2.setEnabled(false);
    jComboBox3.setEnabled(false);
    
}
// TODO add your handling code here:



    
    
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton6.isSelected()){
    jTextField1.setEnabled(false);
   
    
    jComboBox1.setEnabled(false);
    jComboBox2.setEnabled(false);
    jComboBox3.setEnabled(true);
    
}
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Chercheur>a = new  ArrayList<Chercheur>();
       if(buttonGroup1.getSelection().equals(jRadioButton1.getModel())){
            try {
                PreparedStatement st=con.prepareStatement("select cin,nom,nom,prenom,age,email,tel from chercheur where cin=?");
                st.setString(1, jTextField1.getText());
                rs=st.executeQuery();
                
                
                while(rs.next())
                {
                    
                    
                    Chercheur c=new Chercheur(
                            rs.getString("cin"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("age"),
                           
                            rs.getString("email"),
                            rs.getString("tel")
                            
                    );
                    
                    
                    
                    a.add(c);
                    
                    
                    
                    //    }
                }
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage());
            }
     
           
           
           
       }
       if(buttonGroup1.getSelection().equals(jRadioButton3.getModel())){
            try {
                PreparedStatement st=con.prepareStatement("select c.cin,c.nom,c.prenom,c.age,c.email,c.tel from chercheur c,enseignant e where c.cin=e.cin and lower(e.grade)=?");
                st.setString(1, jComboBox1.getSelectedItem().toString().toLowerCase());
                rs=st.executeQuery();
                
                
                while(rs.next())
                {
                    
                    
                    Chercheur c=new Chercheur(
                            rs.getString("cin"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("age"),
                            
                            rs.getString("email"),
                            rs.getString("tel")
                            
                    );
                    
                    
                    
                    a.add(c);
                    
                    
                    
                    //    }
                }
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage());
            }
           
       }
       if(buttonGroup1.getSelection().equals(jRadioButton4.getModel())){
           if(jComboBox2.getSelectedIndex()==0){
               
                try {
                PreparedStatement st=con.prepareStatement("select c.cin,c.nom,c.prenom,c.age,c.email,c.tel from chercheur c,etmastere m where c.cin=m.cin");
               
                rs=st.executeQuery();
                
                
                while(rs.next())
                {
                    
                    
                    Chercheur c=new Chercheur(
                            rs.getString("cin"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("age"),
                           
                            rs.getString("email"),
                            rs.getString("tel")
                            
                    );
                    
                    
                    
                    a.add(c);
                    
                    
                    
                    //    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
           }
           else if(jComboBox2.getSelectedIndex()==1){
                try {
                PreparedStatement st=con.prepareStatement("select c.cin,c.nom,c.prenom,c.age,c.email,c.tel from chercheur c,doctorant d where c.cin=d.cin");
               
                rs=st.executeQuery();
                
                
                while(rs.next())
                {
                    
                    
                    Chercheur c=new Chercheur(
                            rs.getString("cin"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("age"),
                            
                            rs.getString("email"),
                            rs.getString("tel")
                            
                    );
                    
                    
                    
                    a.add(c);
                    
                    
                    
                    //    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
           }
           else if(jComboBox2.getSelectedIndex()==2){
                try {
                PreparedStatement st=con.prepareStatement("select c.cin,c.nom,c.prenom,c.age,c.email,c.tel from chercheur c,enseignant e where c.cin=e.cin");
                
                rs=st.executeQuery();
                
                
                while(rs.next())
                {
                    
                    
                    Chercheur c=new Chercheur(
                            rs.getString("cin"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("age"),
                            
                            rs.getString("email"),
                            rs.getString("tel")
                            
                    );
                    
                    
                    
                    a.add(c);
                    
                    
                    
                    //    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
           }
           
           
           
           else if(jComboBox2.getSelectedIndex()==3){
                try {
                PreparedStatement st=con.prepareStatement("select c.cin,c.nom,c.prenom,c.age,c.email,c.tel from chercheur c,enseignant e where c.cin=e.cin and e.directeur!=?");
                st.setString(1, "0");
                rs=st.executeQuery();
                
                
                while(rs.next())
                {
                    
                    
                    Chercheur c=new Chercheur(
                            rs.getString("cin"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("age"),
                            
                            rs.getString("email"),
                            rs.getString("tel")
                            
                    );
                    
                    
                    
                    a.add(c);
                    
                    
                    
                    //    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
           }
           
           
           
           
           
       }
       if(buttonGroup1.getSelection().equals(jRadioButton6.getModel())){
            try {
                PreparedStatement st=con.prepareStatement("select c.cin,c.nom,c.prenom,c.age,c.email,c.tel from chercheur c ,enseignant e where c.cin=e.cin and lower(e.naturederdiplome)=?");
                st.setString(1, jComboBox3.getSelectedItem().toString().toLowerCase());
                rs=st.executeQuery();
                
                
                while(rs.next())
                {
                    
                    
                    Chercheur c=new Chercheur(
                            rs.getString("cin"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("age"),
                            
                            rs.getString("email"),
                            rs.getString("tel")
                            
                    );
                    
                    
                    
                    a.add(c);
                    
                    
                    
                    //    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
       }
       
       
       if(buttonGroup1.getSelection().equals(jRadioButton2.getModel())){
            try {
                PreparedStatement st=con.prepareStatement("select cin, nom,prenom,tel,age,email from chercheur order by age");
                
                rs=st.executeQuery();
                
                
                while(rs.next())
                {
                    
                    
                    Chercheur c=new Chercheur(
                            rs.getString("cin"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("age"),
                            
                            rs.getString("email"),
                            rs.getString("tel")
                            
                    );
                    
                    
                    
                    a.add(c);
                    
                    
                    
                    //    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
       }
       
       
      
       
       
       
       
       
       
       
       
       
       
       
       
       
       
        DefaultTableModel model = new DefaultTableModel();
     model.setColumnIdentifiers(new Object[]{"CIN","NOM","PRENOM","AGE","EMAIL","TEL"});
     Object[] row = new Object[6];
     
        for(int i=0;i<a.size();i++){
            row[0]=a.get(i).getCin().toUpperCase();
             row[1]=a.get(i).getNom().toUpperCase();
             row[2]=a.get(i).getPren().toUpperCase();
             row[3]=a.get(i).getAge().toUpperCase();
            
             row[4]=a.get(i).getEmail().toUpperCase();
             row[5]=a.get(i).getTel().toUpperCase();
           
            
             model.addRow(row);
        }
        
        jTable1.setModel(model);
       
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new PrevChercheur().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheChercheur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheChercheur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheChercheur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheChercheur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercheChercheur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
