/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Scofield
 */
public class soutenance extends javax.swing.JFrame {

    /**
     * Creates new form soutenance
     */
      Connection con; 
    Statement stmt;
    ResultSet rs;

    public soutenance() {
        initComponents();
        DoConnect();
          }
     private void DoConnect(){
        try{
           Class.forName("com.mysql.jdbc.Driver");
       Connection conn=null;
       
 String url="jdbc:mysql://localhost:3306/laboratoire"; 
 con=DriverManager.getConnection(url,"root","");
 stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
 
 //JOptionPane.showMessageDialog(null, "Succes");
   
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 500));
        setSize(new java.awt.Dimension(840, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ID Enseignant");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 110, 100, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(394, 101, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID Chercheur");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 160, 100, 14);

        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(394, 151, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Type soutenance");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 210, 120, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mastere", "These", "Habilitation" }));
        jComboBox1.setEnabled(false);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(394, 207, 122, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\PROJET JAVA 2\\users_add.png")); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 360, 130, 50);

        jButton2.setText("Valider");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(541, 100, 90, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date soutenance");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 270, 110, 14);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setEnabled(false);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(394, 259, 122, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Lieu soutenance");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 310, 110, 14);

        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(394, 304, 122, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Ajouter Une soutenance");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 20, 300, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("F:\\PROJET JAVA 2\\ajout.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -6, 840, 500);

        jMenu2.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Se deconnecter");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          try {
              // TODO add your handling code here:
              String cin=jTextField1.getText();
              PreparedStatement st=con.prepareStatement("select cin from enseignant where cin=?");
              st.setString(1, cin);
              rs=st.executeQuery();
              if(rs.next()){
                  jTextField2.setEnabled(true);
                  jComboBox1.setEnabled(true);
                  jButton1.setEnabled(true);
                  jDateChooser1.setEnabled(true);
                  jTextField3.setEnabled(true);
              }
              else{
                  JOptionPane.showMessageDialog(this, "Vous n'etes pas un enseignant");
              }
          } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
          }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try {
              // TODO add your handling code here:
              String cinens=jTextField1.getText();
              String cin=jTextField2.getText();
              String type=jComboBox1.getSelectedItem().toString();
              String date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
              String lieu=jTextField3.getText();
              
              PreparedStatement st0=con.prepareStatement("select cin from chercheur where cin=?");
              st0.setString(1, cin);
              rs=st0.executeQuery();
              if(!rs.next()){
                  JOptionPane.showMessageDialog(null,"Ce chercheur n'existe pas");
              }
              else{
              
             if(!verif(cin,type)){
                 JOptionPane.showMessageDialog(null, "Ce chercheur ne peut passer ce type de soutenance");
             }
             else{
                 boolean compatible=true;
                 if(jComboBox1.getSelectedIndex()==0){
                     PreparedStatement ss=con.prepareStatement("SELECT lower (concat(c.prenom,' ',c.nom)) from chercheur c,enseignant e where lower(concat(c.prenom,' ',c.nom))=(select lower(m.enc) from chercheur c,etmastere m where c.cin=m.cin and m.cin=?) and c.cin=e.cin and e.cin=?");
                     ss.setString(1, cin);
                     ss.setString(2, cinens);
                     rs=ss.executeQuery();
                     if(!rs.next())
                         compatible=false;
                 }
                 else{
                    PreparedStatement ss=con.prepareStatement("SELECT lower (concat(c.prenom,' ',c.nom)) from chercheur c,enseignant e where lower(concat(c.prenom,' ',c.nom))=(select lower(d.nomenc) from chercheur c,doctorant d where c.cin=d.cin and d.cin=?) and c.cin=e.cin and e.cin=?");
                     ss.setString(1, cin);
                     ss.setString(2, cinens);
                     rs=ss.executeQuery();
                     if(!rs.next())
                         compatible=false; 
                 }
                 if(!compatible)
                     JOptionPane.showMessageDialog(this, "cet enseignant n'est pas  l'encadrant de ce chercheur !!");
                 else{
              PreparedStatement st=con.prepareStatement("insert into soutenance values(?,?,?,?)");
              st.setString(1, cin);
               st.setString(2, date);
                st.setString(3, lieu);
               st.setString(4, type);
               st.execute();
               JOptionPane.showMessageDialog(null, "soutenance effectue avec succes");
                 }
             }
               
          }
          } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, ex.getMessage());
          }
          
          
          
          
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PrevChercheur().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    public boolean verif(String cin,String type){
        boolean ok=true;
        try {
              
              cin=jTextField2.getText();
              type=jComboBox1.getSelectedItem().toString();
              if(jComboBox1.getSelectedIndex()==0){
              PreparedStatement st=con.prepareStatement("select cin from etmastere where cin=?");
              st.setString(1, cin);
              rs=st.executeQuery();
              if(!rs.next())
                  ok=false;
              }
              else{
                  
               PreparedStatement st=con.prepareStatement("select cin from etmastere where cin=?");
              st.setString(1, cin);
              rs=st.executeQuery();
              if(rs.next())
                  ok=false;
                  
              }
              
           
          } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, ex.getMessage());
          }
             return ok;
    }
    
   
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soutenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soutenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soutenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soutenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new soutenance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
